server:
  port: 8070
eureka:
  client:
    service-url:
      #      注册中心的访问地址  告诉客户端服务的地址（让其知道去哪注册啊）
      defaultZone: http://localhost:8761/eureka/
#      是否将当前服务的ip注册到Eureka Server
spring:
  application:
    name: configclient
